### ISSUE TITLE
Where to place that word vector...root path?

### ISSUE THREAD

**Issue by PremTejaV** [shl5133/E2EECPE#2]

**Comment by PremTejaV** [comment]
Can u explain it in detail as this is my first project..

**Comment by shl5133** [comment]
Root path means: current directory of E2EECPE(i.e. "./").

**Comment by shl5133** [comment]
![image](https://user-images.githubusercontent.com/44437822/103456648-2be48700-4d33-11eb-9d55-c2ed6007b110.png)

**Comment by PremTejaV** [comment]
Where did u executed this project?

**Comment by PremTejaV** [comment]
And should I do any changes in train.py file. I just executed train.py file in Jupyter-Notebook and I got error in line 270. I didn't even imported directory also, just copied and executed that file and wondering where do I place that word vector file mentioned in Usage. I need clarity!!
